

export const SOCKET_CONSTANTS = {
    HEARTBEAT_TIMEOUT : (1000*5),
    HEARTBEAT_VALUE : 1
}


export enum SOCKET_CLIENT_EVENTS{
    JOIN_ROOM="JOIN_ROOM",
    PLAY_MOVE="PLAY_MOVE",
    LEAVE_ROOM="LEAVE_ROOM",
    GET_LATEST_GAME="GET_LATEST_GAME"
}

export enum SOCKET_SERVER_EVENTS{
    JOINED_SUCCESS="JOINED_SUCCESS",
    WAITING_FOR_OTHER_USER="WAITING_FOR_OTHER_USER",
    START_GAME="START_GAME",
    YOUR_TURN="YOUR_TURN",
    WAIT_FOR_YOUR_TURN="WAIT_FOR_YOUR_TURN",
    LEAVE_SUCCESS="LEAVE_SUCCESS",
    LATEST_GAME_STATUS="LATEST_GAME_STATUS"
}


export const SOCKET_GAME_EVENTS = {
    CLIENT:SOCKET_CLIENT_EVENTS,
    SERVER:SOCKET_SERVER_EVENTS
}



export enum SOCKET_MICROSERVICE_EVENTS{
    GET_ROOM_PLAYER_STATUS="GET_ROOM_PLAYER_STATUS"
}

